"""Contrato consumido pelos controllers para obter adaptadores do desktop.

Os métodos constroem tarefas Qt ou consultam o ambiente. Não são regras de
negócio; sessão, preparação e estados continuam nos serviços da aplicação.
"""
from typing import Protocol


class DesktopRuntimePort(Protocol):
    def queue(self, settings, parent=None): ...

    def media_worker(self, *args, **kwargs): ...

    def function_worker(self, operation): ...

    def probe_worker(self, *args, **kwargs): ...

    def hardware_worker(self, tools): ...

    def setup_worker(self): ...

    def engine_worker(self, version): ...

    def thumbnail_worker(self, *args, **kwargs): ...

    def filmstrip_worker(self, *args, **kwargs): ...

    def waveform_worker(self, *args, **kwargs): ...

    def keyframe_worker(self, *args, **kwargs): ...

    def frame_worker(self, project, seconds, size, tools, token, *, text_assets=None): ...
    def interaction_worker(self, plan, size, tools, token, *, text_assets=None): ...

    def playback_worker(
        self,
        project,
        seconds,
        size,
        tools,
        token,
        *,
        fps,
        text_assets=None,
        autostart=True,
    ): ...

    def audio_output(self, parent=None): ...

    def play_audio(self, output, project, seconds, tools, *, text_assets=None, until=None): ...

    def queue_audio(self, output, project, seconds, tools, *, text_assets=None, until=None): ...

    def find_tools(self): ...

    def hardware_ready(self, tools): ...

    def hardware_description(self, preference, tools): ...

    def reset_hardware(self): ...

    @property
    def cookie_browsers(self): ...

    @property
    def engine_version(self): ...

    def is_packaged(self): ...

    @property
    def download_cache(self): ...

    def download_directory(self, settings): ...

    def save_settings(self, settings): ...

    def reveal_file(self, path): ...
