"""Contrato consumido pelos controllers para obter adaptadores do desktop.

Os métodos constroem tarefas Qt ou consultam o ambiente. Não são regras de
negócio; sessão, preparação e estados continuam nos serviços da aplicação.
"""
from typing import Protocol

from PySide6.QtCore import SignalInstance


class PreviewSignals(Protocol):
    """O que a aba de edição escuta de um worker de quadro ou de reprodução.

    ``failed`` faz parte do contrato: sem ele a falha da prévia não chega à
    tela, e o painel não precisa perguntar se o worker o tem.
    """

    frame: SignalInstance
    primed: SignalInstance
    failed: SignalInstance
    done: SignalInstance


class PreviewWorker(Protocol):
    signals: PreviewSignals


class DesktopRuntimePort(Protocol):
    def queue(self, settings, parent=None): ...

    def media_worker(self, *args, **kwargs): ...

    def function_worker(self, operation): ...

    def sample_worker(self, media, target, tools): ...

    def metadata_reader(self, path, tools): ...

    def metadata_writer(self, meta, edit, tools, fallback): ...

    def probe_worker(self, *args, **kwargs): ...

    def hardware_worker(self, tools): ...

    def setup_worker(self): ...

    def engine_worker(self, version): ...

    def thumbnail_worker(self, *args, **kwargs): ...

    def filmstrip_worker(self, *args, **kwargs): ...

    def waveform_worker(self, *args, **kwargs): ...

    def keyframe_worker(self, *args, **kwargs): ...

    def frame_worker(self, project, seconds, size, tools, token, *, text_assets=None) -> PreviewWorker: ...

    def interaction_worker(self, plan, size, tools, token, *, text_assets=None) -> PreviewWorker: ...

    def playback_worker(
        self,
        project,
        seconds,
        size,
        tools,
        token,
        *,
        fps,
        text_assets=None,
        autostart=True,
    ) -> PreviewWorker: ...

    def scrub_cache_worker(self, project, seconds, span, size, tools, token, *, fps, first_index,
                           text_assets=None): ...

    def scrub_cache_budget(self): ...

    def audio_output(self, parent=None): ...

    def play_audio(self, output, project, seconds, tools, *, text_assets=None, until=None): ...

    def queue_audio(self, output, project, seconds, tools, *, text_assets=None, until=None): ...

    def find_tools(self): ...

    def hardware_ready(self, tools): ...

    def hardware_description(self, preference, tools): ...

    def reset_hardware(self): ...

    @property
    def cookie_browsers(self): ...

    @property
    def engine_version(self): ...

    def is_packaged(self): ...

    def start_session(self): ...

    @property
    def download_cache(self): ...

    def close_session(self): ...

    def download_directory(self, settings): ...

    def save_settings(self, settings): ...

    def reveal_file(self, path): ...
